trigger:
  - master
  - dev
  - feature/*
  - bug/*

pool:
  vmImage: "windows-2019"

variables:
  buildConfiguration: "Release"
  netCoreSdk: "2.2.203"

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: build and publish artifact

        steps:
          - script: |
              del FamilyBoardInteractive\proxies.json /q
              ren FamilyBoardInteractive\proxies.server.json proxies.json
            displayName: activate proxies.json server version

          - task: DotNetCoreInstaller@2
            inputs:
              packageType: "sdk"
              version: $(netCoreSdk)

          - task: DotNetCoreCLI@2
            displayName: "dotnet restore"
            inputs:
              command: restore
              projects: "*.sln"

          - task: DotNetCoreCLI@2
            displayName: "dotnet build"
            inputs:
              command: build
              projects: "*.sln"

          - task: DotNetCoreCLI@2
            displayName: "dotnet publish"
            inputs:
              command: publish
              publishWebProjects: True
              arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
              zipAfterPublish: True

          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: "$(Build.ArtifactStagingDirectory)"
              artifactName: "drop"

  - stage: deploy_test
    displayName: deploy to TEST
    dependsOn: build
    variables:
      - group: TEST
    jobs:
      - deployment: TEST
        displayName: deploy to TEST
        environment: TEST
        strategy:
          runOnce:
            deploy:
              steps:
              - download: current
                artifact: drop
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: '$[Deploy.Subscription]'
                  appName: '$[Deploy.FunctionApp]'

  - stage: deploy_prod
    displayName: deploy to PROD
    dependsOn: deploy_test
    variables:
      - group: PROD
    jobs:
      - deployment: PROD
        displayName: deploy to TEST
        environment: PROD
        strategy:
          runOnce:
            deploy:
              steps:
              - download: current
                artifact: drop
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: '$[Deploy.Subscription]'
                  appName: '$[Deploy.FunctionApp]'
