trigger:
  - master
  - dev
  - feature/*
  - bug/*

variables:
  buildConfiguration: "Release"
  netCoreSdk: "2.2.203"

stages:
  - stage: build
    displayName: Build
    pool:
      vmImage: "windows-2019"
    jobs:
      - job: build and publish

        steps:
          - script: |
              del FamilyBoardInteractive\proxies.json /q
              ren FamilyBoardInteractive\proxies.server.json proxies.json
            displayName: activate proxies.json server version

          - task: DotNetCoreInstaller@2
            inputs:
              packageType: "sdk"
              version: $(netCoreSdk)

          - task: DotNetCoreCLI@2
            displayName: "dotnet restore"
            inputs:
              command: restore
              projects: "*.sln"

          - task: DotNetCoreCLI@2
            displayName: "dotnet build"
            inputs:
              command: build
              projects: "*.sln"

          - task: DotNetCoreCLI@2
            displayName: "dotnet publish"
            inputs:
              command: publish
              publishWebProjects: True
              arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
              zipAfterPublish: True

          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: "$(Build.ArtifactStagingDirectory)"
              artifactName: "drop"

  - stage: deploy TEST
    displayName: deploy to TEST
    dependsOn: build
    jobs:
      - deployment: ${{ $parameter.environment }}
        pool:
          vmImage: "windows-2019"
        environment: ${{ $parameter.environment }}
        strategy:
          runOnce:
            display:
              steps:
              - download: current
                artifact: drop
