trigger:
  - master
  - dev
  - feature/*
  - bug/*

pool:
  vmImage: "windows-2019"

variables:
  buildConfiguration: "Release"
  netCoreSdk: "2.2.203"

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: build and publish artifact
        steps:
          - template: azure-piplelines/build.yml

  - stage: deploy_test
    displayName: deploy to TEST
    dependsOn: build
    variables:
      - group: TEST
    jobs:
      - template: azure-piplelines/deploy.yml
        parameters:
          environment: TEST

  - stage: deploy_prod
    displayName: deploy to PROD
    dependsOn: deploy_test
    variables:
      - group: PROD
    jobs:
      - template: azure-piplelines/deploy.yml
        parameters:
          environment: PROD
