name: $(Date:yyyyMMdd)-$(Rev:r)

trigger:
  - master
  - dev
  - feature/*
  - bug/*

stages:
  - stage: build
    displayName: Build
    variables:
      buildConfiguration: 'Release'
      netCoreSdk: '2.2.203'
    jobs:
      - job: build
        displayName: build and publish artifact
        pool:
          vmImage: windows-latest
        workspace:
          clean: all
        steps:
          - template: azure-pipelines/build.yml

  - stage: deploy_test
    displayName: deploy to TEST
    dependsOn: build
    variables:
      - group: 'Test-Deployment'
    jobs:
      - template: azure-pipelines/deploy.yml
        parameters:
          environment: TEST
          agentImage: ubuntu-latest
          functionApp: $(board.functionapp)
          subscription: $(board.subscription)

  - stage: deploy_prod
    displayName: deploy to PROD
    dependsOn: deploy_test
    variables:
      - group: 'Production-Deployment'
    jobs:
      - template: azure-pipelines/deploy.yml
        parameters:
          environment: PROD
          agentImage: ubuntu-latest
          functionApp: $(board.functionapp)
          subscription: $(board.subscription)
