parameters:
  environment: ''

jobs:
  - deployment: ${{ parameters.environment }}
    displayName: deploy to ${{ parameters.environment }} ${{ variables.board.functionapp }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: drop
            - task: AzureWebApp@1
              inputs:
                azureSubscription: ${{ variables.board.subscription }}
                appName: ${{ variables.board.functionapp }}
