parameters:
  environment: ''
  agentImage: 'windows-latest'
  functionApp: ''
  subscription: ''

jobs:
  - deployment: ${{ parameters.environment }}
    displayName: deploy to ${{ parameters.environment }} ${{ parameters.functionApp }}  ${{ parameters.subscription }}
    environment: ${{ parameters.environment }}
    pool:
      vmImage: ${{ parameters.agentImage }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: drop
