parameters:
  environment: ''

jobs:
  - deployment: ${{ parameters.environment }}
    displayName: deploy to ${{ parameters.environment }} $(Deploy.FunctionApp)
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: drop
            - task: AzureWebApp@1
              inputs:
                azureSubscription: '$(Deploy.Subscription)'
                appName: '$(Deploy.FunctionApp)'
