parameters:
  environment: ""

jobs:
  - deployment: ${{ parameter.environment }}
    displayName: deploy to ${{ parameter.environment }}
    environment: ${{ parameter.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: drop
            - task: AzureWebApp@1
              inputs:
                azureSubscription: $(Deploy.Subscription)
                appName: $(Deploy.FunctionApp)
